### PR TITLE
#34 README: updating README infos

### PR DESCRIPTION
**Pull request by nraufu**
> #### What does this PR do?
- add info into README file
> #### Description of Task to be completed
- add features, technologies, and tools used into README
- document API routes functionalities
> #### How should this be manually tested?
- git clone the application URL(`https://github.com/nraufu/portofolio.git`)
- Read me the `README` file
> #### What are the relevant Trello stories?
- https://trello.com/c/AAYOem6v/34-update-readme-file
> #### Screenshots (if appropriate)
readme1

### CODE REVIEW

**Comment by nraufu** [comment]
[Update README file](https://trello.com/c/AAYOem6v/34-update-readme-file)

**Comment by nraufu** [comment]
[Update README file](https://trello.com/c/AAYOem6v/34-update-readme-file)

**Comment by nraufu** [comment]
[Update README file](https://trello.com/c/AAYOem6v/34-update-readme-file)

**Comment by nraufu** [comment]
[Update README file](https://trello.com/c/AAYOem6v/34-update-readme-file)

**Comment by nraufu** [comment]
[Update README file](https://trello.com/c/AAYOem6v/34-update-readme-file)

**Comment by nraufu** [comment]
[Update README file](https://trello.com/c/AAYOem6v/34-update-readme-file)

**Comment by nraufu** [comment]
[hello](https://trello.com/c/NTS8Qlw4/35-hello)

**Comment by nraufu** [comment]
[Update README file](https://trello.com/c/hAwsVABc/36-update-readme-file)

**Review by T2Wil — APPROVED** [review]

**Pull request merged**
