### PR TITLE
#26 admin-signin: admin user login endpoint

### PR DESCRIPTION
**Pull request by nraufu**
> #### What does this PR do?
- adds admin user login
> #### Description of Task to be completed
- add JSON web token package for token
- add model for admin
- return a token upon admin successful authentication
> #### How should this be manually tested?
- git clone the application URL(`https://github.com/nraufu/portofolio.git`)
- run `npm install` then run `npm start`
- create an `env` and store in it SECRET_KEY, ADMINUSERNAME and ADMINPASSWORD values
- open postman and post on `localhost:3000/auth/login` a query with the email and password fields fullfilled
> #### What are the relevant Trello stories?
- https://trello.com/c/2GT73Jby/26-signin-login-endpoint
> #### Screenshots (if appropriate)
login

### CODE REVIEW

**Comment by nraufu** [comment]
[SignIn/Login endpoint](https://trello.com/c/2GT73Jby/26-signin-login-endpoint)

**Comment by T2Wil** [comment]
Nice work @nraufu ,
enclose the response in an object.

raufu_1

**Comment by T2Wil** [comment]
edit the PR description: 
the .env key has to include `SECRET_KEY` not `SECRET`

**Comment by T2Wil** [comment]
nice work!

**Pull request merged**
