### PR TITLE
#33 ch-Swagger documentation: APIs documentation

### PR DESCRIPTION
**Pull request by nraufu**
> #### What does this PR do?
- adds APIs documentation
> #### Description of Task to be completed
- use swagger to document APIs functionality
> #### How should this be manually tested?
- git clone the application URL(`https://github.com/nraufu/portofolio.git`)
- run `npm install` then run `npm start`
- access `https:localhost:3000/api-docs` in the browser
> #### What are the relevant Trello stories?
- https://trello.com/c/CbTf9TPX/33-apis-documentation
> #### Screenshots (if appropriate)
docs
docs1

### CODE REVIEW

**Comment by nraufu** [comment]
[APIs documentation](https://trello.com/c/CbTf9TPX/33-apis-documentation)

**Comment by T2Wil** [comment]
nice work @nraufu

**Comment by nraufu** [comment]
[Update README file](https://trello.com/c/AAYOem6v/34-update-readme-file)

**Comment by nraufu** [comment]
[hello](https://trello.com/c/NTS8Qlw4/35-hello)

**Pull request merged**
